### ISSUE TITLE
Questions about Product List Template / Product Details Page Template

### ISSUE THREAD

**Issue by Maggie2744** [Maggie2744/ecommerce-pattern-library#10]
Hi Thomas (@thomasjbradley),

For my own Product List Page, I have it under a page called Gallery which I've combined a few product listings under...
Am I supposed to create another html page in _layouts to complete this assignment and then have this inputted into Gallery? I am a little confused about how this assignment will work with my pattern library. The same goes for the Product Details Page template assignment.

Thanks!
Maggie

**Comment by thomasjbradley** [comment]
The product list page *is* your `gallery.html`—so finalize that page.

The the product details, you should only be working inside `_layouts/products.html`—but I do see that the code in there is currently incorrect. The basic starter code should look like this:
https://learn-the-web.algonquindesign.ca/courses/web-dev-4/preparing-product-data/#step-3

**Comment by Maggie2744** [comment]
I fixed the Gallery page / product list page template assignment.

I'm almost finished working on the Product Details Page Template, but just have a question.
How can I link my individual product detail pages to the main gallery page with all of the product listings? Is there a specific url variable that I need to put in to link each product individually?

The way I am attempting to connect the two pages is changing the url variable on the "View Product" button in _patterns > cards > product-card.html. I am not sure if this is the proper way of connecting each page specifically though.

Thanks! Let me know if you need more information.

**Comment by thomasjbradley** [comment]
You’ll have to update the pattern include line:
https://github.com/Maggie2744/ecommerce-pattern-library/blob/master/_patterns/cards/product-card.html#L11

```
url=include.data.url
```

**Comment by Maggie2744** [comment]
Hmm. I still get an error when I updated the link.
<img width="468" alt="Screen Shot 2020-03-27 at 6 02 59 PM" src="https://user-images.githubusercontent.com/43113691/77804180-517e8a80-7055-11ea-9480-8bf7cc2dd64e.png">

Its the error I receive when I try clicking on the "View Product" button on the Gallery page.
Would I have to edit the _config.yml file product-card information? 
![Screen Shot 2020-03-27 at 6 12 33 PM](https://user-images.githubusercontent.com/43113691/77804687-89d29880-7056-11ea-80f8-5599997942a5.png)

**Comment by thomasjbradley** [comment]
Get rid of the `"` and `{{` on this line:
https://github.com/Maggie2744/ecommerce-pattern-library/blob/master/_patterns/cards/product-card.html#L11

So it’s just:

```
url=include.data.url
```

**Comment by Maggie2744** [comment]
Perfect! It works!! Thank you so much.

Can I request that Grade for Product Details Page Template again? :)

**Comment by thomasjbradley** [comment]
:star:
