### ISSUE TITLE
Grade for Surprise e-Commerce Page #1

### ISSUE THREAD

**Issue by Maggie2744** [Maggie2744/ecommerce-pattern-library#13]
Hi Thomas (@thomasjbradley),

Overall, I think this coding exercise has proven that I have indeed forgot to code a few integral patterns that had not occurred to me. Such as all of the basic paragraph or table patterns.
The only pattern in my library that was anywhere usable for this kind of content was a section pattern for basic content which had only one type of header and one paragraph. I so badly wanted to recode the pattern to include all of the missing parts but I know that's not allowed.

So! This is all I've got for the Privacy and Terms of Use. I hate it lol. But I definitely learned my lesson on not forgetting small patterns that are integral, such as a pattern with a whole bunch of options for this kind of content. 

Thanks,

Maggie

**Comment by thomasjbradley** [comment]
Thanks for the rationale!
