### ISSUE TITLE
Grade for Surprise e-Commerce Page #2

### ISSUE THREAD

**Issue by Maggie2744** [Maggie2744/ecommerce-pattern-library#14]
Hi Thomas (@thomasjbradley),

I've updated my site to include a bulk pricing page. I think this page does not really go with my site in general because I created a website that was for custom one-off ceramic art pieces instead of bulk products, but that still doesn't take away that I did not have enough patterns to create a proper page. 

Same as the first surprise page, I did not have the right patterns to properly create the new page. It's a great lesson to include every single detail and to not get so focused on the current use of the site and think of future-proofing the patterns (such as the case of my website, where the company could potentially move to bulk pricing).

So yeah. I hate the new page :P but it's finished and I've learned a lot. 

Thanks,
Maggie

**Comment by thomasjbradley** [comment]
Haha. Thanks for the rationale.
