### ISSUE TITLE
Grade for Building Pages with Patterns

### ISSUE THREAD

**Issue by Maggie2744** [Maggie2744/ecommerce-pattern-library#2]
Hi Thomas  @thomasjbradley

I've finished the requirements for editing the highlight of the main navigation. The only question I had was to find out if there is a way to "download" different text-decoration elements into Atom? I seem to only have a few options that function with Atom and affect my nav .current highlight. 

If not, I've styled it in a way that is distinguishable. 

Thanks,
Maggie

**Comment by thomasjbradley** [comment]
Looks fantastic.

Don’t worry if Atom understands those properties or not. As long as they are working the browser that’s what we care about.

As for auto-complete, unfortunately we can only wait for the developers of Atom to update their highlighting system to understand the new text-decoration properties.

**Comment by Maggie2744** [comment]
Perfect. Thanks!
