### ISSUE TITLE
Grade for The Leftovers

### ISSUE THREAD

**Issue by Maggie2744** [Maggie2744/ecommerce-pattern-library#3]
Hi Thomas @thomasjbradley

I've added the remainder of elements that are needed to complete my ecommerce website (including elements for the About and Social pages). I had a question about where to code the accessibility html. Should it be implemented on the main html pages themselves (e.g. index.html, gallery.html) or should they be implemented on each individual pattern element (e.g. banner.html, section.html)?

Thanks,
Maggie

**Comment by thomasjbradley** [comment]
What accessibility HTML specifically? 

- Skip links should be at the top of each page, like at the top of `index.html` & `products.html`
- The rest most likely needs to be embedded in the patterns themselves.

**Comment by Maggie2744** [comment]
Hi Thomas,

It looks like I've figured out where to put the skip-links, ARIA landmarks, and everything else :) 
I hope that it completed the requirements for this assignment.

Thanks!
Maggie

**Comment by thomasjbradley** [comment]
I’ve checked it off.

**Comment by Maggie2744** [comment]
thanks!!
