### ISSUE TITLE
Grade for Markdown Multiplier

### ISSUE THREAD

**Issue by Maggie2744** [Maggie2744/ecommerce-pattern-library#7]
Hi Thomas @thomasjbradley,

I've attached a screenshot of the success screen after completing the Mardown Multiplier quiz.
Disregard the time.... it did not take me that long to finish :P 
I took a break to walk the dog halfway through lol.

Thanks,
Maggie
<img width="1440" alt="Successful Markdown Multiplier" src="https://user-images.githubusercontent.com/43113691/77259022-e435b880-6c54-11ea-9248-488ce198a25f.png">

**Comment by thomasjbradley** [comment]
That’s quite a long time!
