### ISSUE TITLE
Grade for YAML Yodeller

### ISSUE THREAD

**Issue by Maggie2744** [Maggie2744/ecommerce-pattern-library#8]
Hi Thomas @thomasjbradley,

Here is my success page for completing the YAML Yodeller quiz!
I hope your dog starts to feel comfortable soon. Sorry to hear that he/she has health problems.

Thanks,
Maggie
<img width="1436" alt="YAML Yodeller Success Page" src="https://user-images.githubusercontent.com/43113691/77463967-d9a62b00-6ddc-11ea-972f-1d3dd58ea23f.png">

**Comment by thomasjbradley** [comment]
Thanks!
